# Generated by Django 3.1.6 on 2021-03-08 17:31

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_auto_20210217_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 17, 30, 17, 959334, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated'),
            preserve_default=False,
        ),
    ]
