# Generated by Django 3.1.6 on 2021-03-25 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_auto_20210325_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 16, 37, 8, 338376, tzinfo=utc)),
        ),
    ]
