# Generated by Django 3.1.6 on 2021-03-25 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_auto_20210326_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='amounts',
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 17, 49, 24, 361958, tzinfo=utc)),
        ),
    ]
