# Generated by Django 3.1.6 on 2021-03-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0015_auto_20210329_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='settled',
            field=models.BooleanField(default=True),
        ),
    ]
