# Generated by Django 3.1.6 on 2021-04-01 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0016_transaction_settled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='client_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.client_account'),
        ),
    ]
