# Generated by Django 3.1.6 on 2021-04-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0019_auto_20210403_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_account',
            name='balance',
        ),
    ]
