# Generated by Django 3.1.6 on 2021-04-06 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0020_remove_client_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='received',
        ),
    ]
