# Generated by Django 3.1.6 on 2021-04-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0022_running_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type_code',
            field=models.CharField(default='test', max_length=5),
            preserve_default=False,
        ),
    ]
