# Generated by Django 3.1.6 on 2021-04-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0023_transaction_type_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='client_code',
            field=models.CharField(default='cli_code', max_length=20),
            preserve_default=False,
        ),
    ]
