# Generated by Django 3.1.6 on 2021-04-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0024_account_client_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='client_code',
            field=models.CharField(max_length=20),
        ),
    ]
