# Generated by Django 3.1.6 on 2021-04-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0026_remove_account_client_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='client_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
