# Generated by Django 3.1.6 on 2021-04-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0028_account_subject_matter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='subject_matter',
            field=models.TextField(null=True),
        ),
    ]
