# Generated by Django 3.1.6 on 2021-04-20 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0029_auto_20210415_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='running_balance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
