# Generated by Django 3.1.6 on 2021-04-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0031_auto_20210423_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_account',
            name='acc_number',
            field=models.CharField(default=123, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client_account',
            name='bank_code',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client_account',
            name='bank_name',
            field=models.CharField(default='bankbank', max_length=120),
            preserve_default=False,
        ),
    ]
