# Generated by Django 3.1.6 on 2021-04-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0032_auto_20210423_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='client_account',
            field=models.BooleanField(default=True),
        ),
    ]
