# Generated by Django 3.1.6 on 2021-04-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0033_auto_20210427_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='client_account',
        ),
    ]
