# Generated by Django 3.1.6 on 2021-04-27 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0035_account_client_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='running_balance',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.transaction'),
        ),
    ]
