# Generated by Django 3.1.6 on 2021-05-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0038_auto_20210430_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amounts',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type_codes',
        ),
        migrations.AddField(
            model_name='transaction',
            name='table_list',
            field=models.TextField(default='holder'),
            preserve_default=False,
        ),
    ]
