# Generated by Django 3.1.6 on 2021-08-06 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0039_auto_20210518_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ad_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_link', to='ledger.account'),
        ),
    ]
