# Generated by Django 3.1.6 on 2021-08-09 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0040_transaction_ad_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ad_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cli_ad_link', to='ledger.transaction'),
        ),
    ]
