# Generated by Django 3.1.6 on 2021-11-18 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0041_auto_20210809_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cli_acc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ledger.client_account'),
            preserve_default=False,
        ),
    ]
