# Generated by Django 3.1.6 on 2021-11-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0042_transaction_cli_acc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cli_acc',
        ),
    ]
