# Generated by Django 3.1.6 on 2021-11-18 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0043_remove_transaction_cli_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cli_acc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ledger.client_account'),
        ),
    ]
