# Generated by Django 3.1.6 on 2021-11-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0044_transaction_cli_acc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
