# Generated by Django 3.1.6 on 2021-12-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0045_type_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_code',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
