# Generated by Django 3.1.6 on 2021-12-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0046_auto_20211201_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='off_received',
            field=models.BooleanField(null=True),
        ),
    ]
