# Generated by Django 3.1.6 on 2021-12-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0047_transaction_off_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='off_received',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cleared',
            field=models.BooleanField(default=True),
        ),
    ]
