# Generated by Django 3.1.6 on 2021-12-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0048_auto_20211202_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
