# Generated by Django 3.1.6 on 2021-12-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0049_transaction_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='file_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
