# Generated by Django 3.1.6 on 2021-12-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0050_auto_20211227_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='subject_matters',
            field=models.TextField(null=True),
        ),
    ]
