# Generated by Django 3.1.6 on 2021-12-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0051_account_subject_matters'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subj_matter',
            field=models.TextField(null=True),
        ),
    ]
