# Generated by Django 3.1.6 on 2021-12-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0052_transaction_subj_matter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='subject_matters',
            new_name='subj_list',
        ),
    ]
