# Generated by Django 3.1.6 on 2022-02-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0054_type_code_for_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='closing_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_date',
            field=models.DateField(null=True),
        ),
    ]
