# Generated by Django 3.1.6 on 2022-02-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0055_auto_20220209_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='closing_no',
            field=models.TextField(null=True),
        ),
    ]
