# Generated by Django 3.1.6 on 2022-02-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0056_account_closing_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vouch_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
