# Generated by Django 3.1.6 on 2022-02-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0057_auto_20220210_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='off_vouch_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
