# Generated by Django 3.1.6 on 2022-02-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0059_auto_20220210_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='off_vouch_no',
            new_name='off_voucher_no',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='vouch_no',
            new_name='voucher_no',
        ),
    ]
