# Generated by Django 3.1.6 on 2022-02-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0061_auto_20220211_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='off_voucher_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receipt_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='voucher_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
