# Generated by Django 3.1.6 on 2022-02-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0062_auto_20220214_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='other_list',
            field=models.TextField(null=True),
        ),
    ]
