# Generated by Django 3.1.6 on 2026-03-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0064_auto_20220312_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='custom_file_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='custom_payee',
            field=models.TextField(null=True),
        ),
    ]
