# Generated by Django 3.1.6 on 2021-03-09 06:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210309_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='file_no',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 6, 40, 2, 38718, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
