# Generated by Django 3.1.6 on 2021-03-12 11:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210309_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 11, 17, 30, 341651, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='date updated'),
        ),
    ]
