# Generated by Django 3.1.6 on 2021-03-24 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210313_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='descriptions',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 17, 21, 26, 290470, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.TextField(),
        ),
    ]
