# Generated by Django 3.1.6 on 2021-03-25 06:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210325_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 6, 41, 16, 459166, tzinfo=utc)),
        ),
    ]
