# Generated by Django 3.1.6 on 2021-03-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20210327_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cheque_text',
            field=models.TextField(default='cold hard cash'),
            preserve_default=False,
        ),
    ]
