# Generated by Django 3.1.6 on 2021-03-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_transaction_cheque_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cheque_text',
            field=models.TextField(null=True),
        ),
    ]
